---
title: 遗书
date: 2025-02-27 21:39:28
tags: 纪年史
---

   如果你读到了这遗书，那我肯定已经去世了，会是什么原因呢？我也不知道。大概你会听说我离开的原因吧。人生总是充满意外的，倘我哪天不在了也属正常。所以，我提前留下一些话给你们。

   在我活着的岁月里，我感受到很多。现在，我想起幼儿园里上课时独自玩耍的跷跷板；想起在小学氤氲雾气中玩的捉迷藏；想起我去那间黑洞洞的屋子里看老爷爷的日子，又记起他坐在一棵小枣树下看着我的慈祥模样，阳光透过叶子间隙照在他的脸上；想起我小时候在奶奶家喝的这辈子最好喝的丝瓜汤，我就着吃了四个大馒头；想起每次离开家的时候，总是去爷爷奶奶家坐坐，听他们讲讲过去的故事，无论是历史轶事还是民间传说；说起枣树，我初中时国庆放假写的打枣的作文被老师夸了，那时历历在目，我爬到房顶上晃着枣枝，姥爷在下面捡落下的枣子，我又念起姥爷做的蹦枣（酒枣），自姥爷走后，再没尝过。后来想姥爷了就去那片地里看看，磕两个头，可说不出话，火车自顾自的从旁边开过，犹记起小时和姥爷在铁道旁放羊的时候；想起了初中时在房顶上瑟瑟发抖看天琴座流星雨，因偶然拍到流星而喜欢天文的我；想起了曾经有个眼睛会说话的姑娘爱我，眼眸星云，灿若桃花；想起“长太息以掩涕兮，哀民生之多艰”，百姓多艰难呦，多想“安得广厦千万间，大庇天下寒士俱欢颜”，可年纪愈大，自身难保；想起好多好多夏天，好多好多蝉鸣；想起好多好多冬天，雪从厚厚一层被晒得薄薄的，雪水泥泞，雪人流泪；想起我妈眉尾上扬，向外人傲娇夸我的样子；想起我爸在我压力睡不着时，跟我说，没事，爸能养你一辈子；想起小时候和姐姐打架，又看着姐姐出嫁，后来可爱的小外甥也出生了，会喊了舅舅；想起每次去姥姥家，姥姥都偷偷塞钱给我，不让我说出去......真好哇，谁不留恋呢，可终究结束了呢。

   希望你们好好珍惜当下的日子，注意身体健康。无论现在多么艰难，都要对自己好一点，总有人爱你，总要爱自己，不要做傻事。

   所以有人会怀念我吗？有人会因为我的离开一瞬间恍惚而又悲伤吗？

   在以前的日子里，我总是做错很多事情，会有人原谅我吗？好像没什么意义，因我已经死了，所以倘这怨恨让人痛快，便自顾怨恨去，不妨事。

   我写了一些关于我的东西，如果你喜欢的话，可以去看看。我一直觉得，文字是不朽的，哪怕我的身躯已经腐烂，可我的文字不会。或好或坏，都比我活的长久。于是，我便也活在我的文字里，文字里活着真的我。

   对不起，我的朋友们，我无法向你们描述死亡是什么样的感受，即使我很想那么做。我的体验已无法说出口，多么令人遗憾。我还能看到你们吗？我是否变成天上的星星，变成亘古永恒的东西？我还是去往地府轮回转世投胎呢？下辈子会变成什么呢？

   若有人真的因我离去而悲伤，我或许对你很重要吧，让你为我的离去伤心，可我又因为嘴笨而无法劝慰你了。真可恶哇，我该怎么劝慰你呢？让我上愁。若看你流泪，我也会流泪的。虽已见不到了，可我仍然祝福你，希望你不要因为我沉湎于悲伤，快快振奋起来，过自己的日子去。若看你开心，我也自然开心。

   遗书像我的生命一样，总有尽头。
   万般不舍，总归要说再见。
   我走了。

   2025.2.27 （最后修改时间）

   孙祥和